### PR TITLE
Show done actions in project view & two UI tweaks

### PR DESCRIPTION
**Pull request by simonbaird**

### CODE REVIEW

**Comment by simonbaird** [comment]
Actually don't merge this, I just noticed it causes extra "Completed Actions" sections to appear in other dashboards.

**Comment by simonbaird** [comment]
Still needs some work to fix sorting.

Let me know if you think the sorting of completed items by completed date should be enabled with a setting.

**Comment by simonbaird** [comment]
Okay commit bcbed19 is working okay.

**Comment by roma0104** [comment]
@simonbaird Thanks for you work Simon.  I will take a look at this tonight.  I think your sort by `gsd_comp_date` will still suffer from #46.  When I wrote the date sorts I hadn't noticed the design of the eachday and sameday filter would cause problems.  I have a patch to fix the issue in TW5 but just awaiting Jeremy's approval. https://github.com/Jermolene/TiddlyWiki5/pull/1520  Otherwise we can just patch it and overwrite from our end for now, though I would like to avoid it.

**Comment by simonbaird** [comment]
A quick demo here:
http://randomibis.com/gsd5-completed-tweaks-demo.html#Action%20Dashboard:%5B%5BAction%20Dashboard%5D%5D%20SomeProject

Don't merge this in any case.

I'll put "Fix missing colon typo" in a new PR.

**Comment by simonbaird** [comment]
Should probably be cut up into separate pull requests.

**Comment by simonbaird** [comment]
Apologies, that wasn't very tidy.

**Comment by simonbaird** [comment]
But thanks for the merge. :)

**Comment by roma0104** [comment]
Thank you for your contributions.  I wasn't sure if you were working on something related to this pull so I left it open.  But everything committed looked stand-alone.  

Given my skill with git and coding, it is surprising this thing actually works and some else project hasn't shown up in the repo too.

**Pull request merged**
